In [3]:
# Descarga los datasets para vinos tintos y blancos desde la siguiente URL: [Wine Quality Dataset](http://archive.ics.uci.edu/dataset/186/wine+quality).

import pandas as pd

In [9]:
# Asegúrate de que ambos datasets se encuentren disponibles en tu entorno de trabajo como archivos CSV. Compruebo si están los archivos CSV en la ubicación esperada, en la carpeta de PC!_GRUPO_2.

import os
print(os.listdir())

['.anaconda', '.bash_history', '.conda', '.condarc', '.continuum', '.git', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.lesshst', '.matplotlib', '.spyder-py3', '.viminfo', '.virtual_documents', '.vscode', 'anaconda3', 'anaconda_projects', 'AppData', 'Configuración local', 'Contacts', 'Cookies', 'Datos de programa', 'Desktop', 'Documents', 'Downloads', 'Dropbox', 'Entorno de red', 'Favorites', 'IdeaProjects', 'Impresoras', 'Links', 'Menú Inicio', 'Mis documentos', 'Music', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{9b9724a7-aae1-11ef-82b1-ab91082f2138}.TM.blf', 'NTUSER.DAT{9b9724a7-aae1-11ef-82b1-ab91082f2138}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{9b9724a7-aae1-11ef-82b1-ab91082f2138}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'OneDrive - MBIT School', 'PC1', 'PC1_GRUPO_2.ipynb', 'Pictures', 'Plantillas', 'Reciente', 'Saved Games', 'Searches', 'SendTo', 'Taller_de_Python', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled6.ipynb', 'Videos']

In [25]:
# Usa Pandas para cargar ambos datasets en dataframes en memoria.

import pandas as pd

# Me descargo y guardo los datasets en una carpeta que llamo data dentro de PC1_GRUPO_2 "PC1_GRUPO_2/data/"
df_red = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")
df_white = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep=";")

print("Archivos descargados y guardados correctamente en PC1_proyecto/data/")

Archivos descargados y guardados correctamente en PC1_proyecto/data/

In [27]:
# Muestro las primeras filas para ver la estructura

df_red.head(), df_white.head()

(   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0            7.4              0.70         0.00             1.9      0.076
 1            7.8              0.88         0.00             2.6      0.098
 2            7.8              0.76         0.04             2.3      0.092
 3           11.2              0.28         0.56             1.9      0.075
 4            7.4              0.70         0.00             1.9      0.076

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
 0                 11.0                  34.0   0.9978  3.51       0.56
 1                 25.0                  67.0   0.9968  3.20       0.68
 2                 15.0                  54.0   0.9970  3.26       0.65
 3                 17.0                  60.0   0.9980  3.16       0.58
 4                 11.0                  34.0   0.9978  3.51       0.56

    alcohol  quality
 0      9.4        5
 1      9.8        5
 2      9.8        5
 3      9.8        6
 4      9.4        5  ,
    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0            7.0              0.27         0.36            20.7      0.045
 1            6.3              0.30         0.34             1.6      0.049
 2            8.1              0.28         0.40             6.9      0.050
 3            7.2              0.23         0.32             8.5      0.058
 4            7.2              0.23         0.32             8.5      0.058

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
 0                 45.0                 170.0   1.0010  3.00       0.45
 1                 14.0                 132.0   0.9940  3.30       0.49
 2                 30.0                  97.0   0.9951  3.26       0.44
 3                 47.0                 186.0   0.9956  3.19       0.40
 4                 47.0                 186.0   0.9956  3.19       0.40

    alcohol  quality
 0      8.8        6
 1      9.5        6
 2     10.1        6
 3      9.9        6
 4      9.9        6  )

In [55]:
df_red.shape

(1599, 13)

In [61]:
df_white.shape

(4898, 13)

In [33]:
filas, columnas = df_red.shape
print(f"El dataframe de vinos tintos tiene {filas} filas y {columnas} columnas")

filas, columnas = df_white.shape
print(f"El dataframe de vinos blancos tiene {filas} filas y {columnas} columnas")

El dataframe de vinos tintos tiene 1599 filas y 12 columnas
El dataframe de vinos blancos tiene 4898 filas y 12 columnas

In [37]:
# Añade una columna adicional que indique el tipo de vino (`red` o `white`). 

df_red["tipo_de_vino"] = "tinto"

df_red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,tipo_de_vino
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,blanco
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,blanco
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,blanco
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,blanco
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,blanco

In [39]:
df_white["tipo_de_vino"] = "blanco"

df_white.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,tipo_de_vino
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,blanco
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,blanco
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,blanco
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,blanco
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,blanco

In [43]:
# Combina los datos en un único dataframe con la nueva columna.

df_vino_tinto_y_blanco = pd.concat([df_red, df_white])

df_vino_tinto_y_blanco.head

<bound method NDFrame.head of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076
1               7.8              0.88         0.00             2.6      0.098
2               7.8              0.76         0.04             2.3      0.092
3              11.2              0.28         0.56             1.9      0.075
4               7.4              0.70         0.00             1.9      0.076
...             ...               ...          ...             ...        ...
4893            6.2              0.21         0.29             1.6      0.039
4894            6.6              0.32         0.36             8.0      0.047
4895            6.5              0.24         0.19             1.2      0.041
4896            5.5              0.29         0.30             1.1      0.022
4897            6.0              0.21         0.38             0.8      0.020

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56
1                    25.0                  67.0  0.99680  3.20       0.68
2                    15.0                  54.0  0.99700  3.26       0.65
3                    17.0                  60.0  0.99800  3.16       0.58
4                    11.0                  34.0  0.99780  3.51       0.56
...                   ...                   ...      ...   ...        ...
4893                 24.0                  92.0  0.99114  3.27       0.50
4894                 57.0                 168.0  0.99490  3.15       0.46
4895                 30.0                 111.0  0.99254  2.99       0.46
4896                 20.0                 110.0  0.98869  3.34       0.38
4897                 22.0                  98.0  0.98941  3.26       0.32

      alcohol  quality tipo_de_vino
0         9.4        5        tinto
1         9.8        5        tinto
2         9.8        5        tinto
3         9.8        6        tinto
4         9.4        5        tinto
...       ...      ...          ...
4893     11.2        6       blanco
4894      9.6        5       blanco
4895      9.4        6       blanco
4896     12.8        7       blanco
4897     11.8        6       blanco

[6497 rows x 13 columns]>

In [59]:
# ¿Cuántos registros tenemos?
# Miro la forma y compruebo que haya tantas filas o registros como la suma del número de filas de tintos y blancos de las tablas anteriores, cuando los vinos estaban separados por color. Coincide. Hay 6497 filas, que corresponden a 1599 vinos tintos y 4898 vinos blancos, como habíamos comprobado anteriormente. 
df_vino_tinto_y_blanco.shape

(6497, 13)

In [57]:
# ¿Cuántas variables y de qué tipo?
df_vino_tinto_y_blanco.info()

# Hay 13 variables: fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, quality, tipo_de_vino. 11 de ellas son valores numéricos con decimales, la acidez, la densidad, el alcohol ... Una de ellas, la calidad, es numérica sin decimales. Y la variable que hemos creado es un texto, rojo o blanco. Al emplear este comando además nos informa de que no hay valores null, es decir, todas las filas tienen datos en todas las columnas.

<class 'pandas.core.frame.DataFrame'>
Index: 6497 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  tipo_de_vino          6497 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 710.6+ KB

In [53]:
df_vino_tinto_y_blanco.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'tipo_de_vino'],
      dtype='object')

In [67]:
# Realiza un análisis estadístico o inspección visual de cada columna numérica para identificar valores atípicos. 
# Usa Pandas para filtrar y eliminar los datos atípicos y los valores ausentes. Explica en tu entrega qué criterios utilizaste para identificar los atípicos.


# Primero voy a ver de nuevo la tabla con la que estoy trabajando y a crear una copia para guardar el DataFrame, puesto que hemos creado uno nuevo df_vino_tinto_y_blanco, a partir de df_red y df_white

print (df_vino_tinto_y_blanco)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076
1               7.8              0.88         0.00             2.6      0.098
2               7.8              0.76         0.04             2.3      0.092
3              11.2              0.28         0.56             1.9      0.075
4               7.4              0.70         0.00             1.9      0.076
...             ...               ...          ...             ...        ...
4893            6.2              0.21         0.29             1.6      0.039
4894            6.6              0.32         0.36             8.0      0.047
4895            6.5              0.24         0.19             1.2      0.041
4896            5.5              0.29         0.30             1.1      0.022
4897            6.0              0.21         0.38             0.8      0.020

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56
1                    25.0                  67.0  0.99680  3.20       0.68
2                    15.0                  54.0  0.99700  3.26       0.65
3                    17.0                  60.0  0.99800  3.16       0.58
4                    11.0                  34.0  0.99780  3.51       0.56
...                   ...                   ...      ...   ...        ...
4893                 24.0                  92.0  0.99114  3.27       0.50
4894                 57.0                 168.0  0.99490  3.15       0.46
4895                 30.0                 111.0  0.99254  2.99       0.46
4896                 20.0                 110.0  0.98869  3.34       0.38
4897                 22.0                  98.0  0.98941  3.26       0.32

      alcohol  quality tipo_de_vino
0         9.4        5        tinto
1         9.8        5        tinto
2         9.8        5        tinto
3         9.8        6        tinto
4         9.4        5        tinto
...       ...      ...          ...
4893     11.2        6       blanco
4894      9.6        5       blanco
4895      9.4        6       blanco
4896     12.8        7       blanco
4897     11.8        6       blanco

[6497 rows x 13 columns]

In [71]:
df_vino_completo = df_vino_tinto_y_blanco.copy()

In [75]:
print (df_vino_completo)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076
1               7.8              0.88         0.00             2.6      0.098
2               7.8              0.76         0.04             2.3      0.092
3              11.2              0.28         0.56             1.9      0.075
4               7.4              0.70         0.00             1.9      0.076
...             ...               ...          ...             ...        ...
4893            6.2              0.21         0.29             1.6      0.039
4894            6.6              0.32         0.36             8.0      0.047
4895            6.5              0.24         0.19             1.2      0.041
4896            5.5              0.29         0.30             1.1      0.022
4897            6.0              0.21         0.38             0.8      0.020

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56
1                    25.0                  67.0  0.99680  3.20       0.68
2                    15.0                  54.0  0.99700  3.26       0.65
3                    17.0                  60.0  0.99800  3.16       0.58
4                    11.0                  34.0  0.99780  3.51       0.56
...                   ...                   ...      ...   ...        ...
4893                 24.0                  92.0  0.99114  3.27       0.50
4894                 57.0                 168.0  0.99490  3.15       0.46
4895                 30.0                 111.0  0.99254  2.99       0.46
4896                 20.0                 110.0  0.98869  3.34       0.38
4897                 22.0                  98.0  0.98941  3.26       0.32

      alcohol  quality tipo_de_vino
0         9.4        5        tinto
1         9.8        5        tinto
2         9.8        5        tinto
3         9.8        6        tinto
4         9.4        5        tinto
...       ...      ...          ...
4893     11.2        6       blanco
4894      9.6        5       blanco
4895      9.4        6       blanco
4896     12.8        7       blanco
4897     11.8        6       blanco

[6497 rows x 13 columns]

In [77]:
df_vino_completo.shape

(6497, 13)

In [ ]:
# Empezamos con un análisis estadístico o inspección visual de cada columna numérica para identificar valores atípicos. 
# Necesito identificar el problema que vamos a resolver, o las hipótesis que planteamos para correborrar. En mi caso, me gustaría saber qué vinos son de mayor calidad, si los tintos o los blancos, cuál es el promedio de calidad general y por tipo de vino, así como el nivel de alcohol promedio por tipo de vino. 
# Ya conocemos algo de los datos que tenemos, sabemos que hay 6497 tipos de vino, que hay 13 variables recogidas de cada uno de ellos, la mayoría con números reales, excepto la calidad que son números enteros y la columna que hemos añadido que es texto dicotómico. 
# Vamo a realizar un análisis estadístico de cada columna para identificar atípicos, haremos medidas de tendencia central y dispersión para poder detecar datos muy dispersos.